apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-password: {{ .Values.auth.rootPassword | quote }}
  database: {{ .Values.auth.database | quote }}
  username: {{ .Values.auth.user | quote }}
  password: {{ .Values.auth.password | quote }}
