app:
  image:
    registry: ""
    repository: fastack/app
    tag: latest
    pullPolicy: IfNotPresent

worker:
  image:
    registry: ""
    repository: fastack/worker
    tag: latest
    pullPolicy: IfNotPresent
  database:
    host: "{{ .Release.Name }}-mariadb-service"
    port: 3306
    name: appdb
    user: appuser
    password:
      value: apppassword

  mariadb:
  image:
    registry: ""
    repository: fastack/mariadb
    tag: latest
    pullPolicy: IfNotPresent
  auth:
    rootPassword:
      existingSecretName: null
      existingSecretKey: null
      value: rootpassword
    database: appdb
    user: appuser
    password:
      existingSecretName: null
      existingSecretKey: null
      value: apppassword
