image:
  repository: fastack/worker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  - name: DB_HOST
    value: mariadb
  - name: DB_PORT
    value: "3306"
  - name: DB_USER
    value: appuser
  - name: DB_PASSWORD
    value: apppassword
  - name: DB_NAME
    value: appdb
