image:
  registry: ""
  repository: fastack/worker
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

database:
  host: "{{ .Release.Name }}-mariadb-service"
  port: 3306
  name: appdb
  user: appuser
  password:
    existingSecret: null
    existingSecretKey: null
    value: apppassword

env: []
