services:
  app:
    image: '[[ published_image("app", "fastack/app") ]]'
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress
    networks:
      - fastack

networks:
  fastack:
    driver: overlay
