replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  registry: ""
  repository: "[[ join('shared', 'mariadb') ]]"
  pullPolicy: IfNotPresent
  tag: latest

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3306

  auth:
  rootPassword:
    existingSecretName: null
    existingSecretKey: null
    value: rootpassword
  database: appdb
  user: appuser
  password:
    existingSecretName: null
    existingSecretKey: null
    value: apppassword

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
