replicaCount: 1

image:
  repository: fastack/mariadb
  pullPolicy: IfNotPresent
  tag: latest

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 3306

auth:
  rootPassword: rootpassword
  database: appdb
  user: appuser
  password: apppassword

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
