services:
  worker:
    image: '[[ published_image("worker", "fastack/worker") ]]'
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: appdb
    ports:
      - target: 8000
        published: 8001
        protocol: tcp
        mode: ingress
    networks:
      - fastack

networks:
  fastack:
    driver: overlay
