replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  registry: ""
  repository: "[[ join(target.registry, project.name, 'fastack/worker') ]]"
  pullPolicy: IfNotPresent
  tag: "[[ artifact.version ]]"

  database:
  host: "{{ .Release.Name }}-mariadb-service"
  port: 3306
  name: appdb
  user: appuser
  password:
    existingSecretName: null
    existingSecretKey: null
    value: null

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000

env: []

probes:
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
